# -*- coding: utf-8 -*-
"""CSc740_Fall_2023_Final_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15LI9pK9nv9U_U6sfxr_wlDjF1JUJdGxY

# Imports
"""

import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

"""# Data & Processing"""

# LIST TO DOWNLOAD\
"""

https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&Cycle=2017-2020


 Alcohol Use
 Blood Pressure & Cholesterol
 Cardiovascular Health
 Current Health Status
 Diabetes
 Immunization
 Income...?
 Medical Conditions
 Mental Health - Depression Screener?
 Physical Activity
 Sleep Disorders
 Smoking - Cigarette Use
 Smoking - Secondhand Smoke Exposure
"""

"""# DATAFRAMES AND CLEANING"""

questionnaire_codes_17_18 = ["ALQ_J", "BPQ_J", "CDQ_J", "HSQ_J", "DIQ_J",
                             "IMQ_J", "INQ_J", "MCQ_J", "PAQ_J", "DPQ_J", "SMQ_J", "SMQSHS_J"]
questionnaire_codes_15_16 = ["ALQ_I", "BPQ_I", "CDQ_I", "HSQ_I", "DIQ_I",
                             "IMQ_I", "INQ_I", "MCQ_I", "PAQ_I", "DPQ_I", "SMQ_I", "SMQSHS_I"]
questionnaire_codes_13_14 = ["ALQ_H", "BPQ_H", "CDQ_H", "HSQ_H", "DIQ_H",
                             "IMQ_H", "INQ_H", "MCQ_H", "PAQ_H", "DPQ_H", "SMQ_H", "SMQSHS_H"]


def get_dataframe(code):
    return pd.read_sas('data/%s.XPT' % code, format='xport', encoding="utf-8")


frames_13_14 = list(
    map(lambda x: get_dataframe(x), questionnaire_codes_13_14))

frames_15_16 = list(
    map(lambda x: get_dataframe(x), questionnaire_codes_15_16))

frames_17_18 = list(
    map(lambda x: get_dataframe(x), questionnaire_codes_17_18))

"""# COMBINE ALL DATA"""

# shape has 364 columns instead of 269 in downloaded version?
NHANES_13_14 = reduce(lambda left, right: pd.merge(left, right, on=['SEQN'],
                                                   how='outer'), frames_13_14)

NHANES_15_16 = reduce(lambda left, right: pd.merge(left, right, on=['SEQN'],
                                                   how='outer'), frames_15_16)

NHANES_17_18 = reduce(lambda left, right: pd.merge(left, right, on=['SEQN'],
                                                   how='outer'), frames_17_18)


# Standardize columns
columns_df1 = set(NHANES_13_14.columns)
columns_df2 = set(NHANES_15_16.columns)
columns_df3 = set(NHANES_17_18.columns)

common_columns = list(columns_df1 & columns_df2 & columns_df3)
NHANES_13_14 = NHANES_13_14[common_columns]
NHANES_15_16 = NHANES_15_16[common_columns]
NHANES_17_18 = NHANES_17_18[common_columns]
